# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Generate data

on:
  #schedule:
  #  - cron: "0 * * * *"    # every hour (UTC)
  workflow_dispatch: {}    # allow manual run

jobs:
  build-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo ${{ secrets.CLIENT_ID }}
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
          echo "USER_NAME=${{ secrets.USERNAME }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "ACCESS_TOKEN_FILE=${{ secrets.ACCESS_TOKEN_FILE }}" >> .env

      - name: Generate TRP members data
        run: npm run data trp-members
      #- name: Upload generated data
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: generated-data
      #    path: data/

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/
          git commit -m 'chore: update generated data' || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}

  build-ui:
    needs: build-data
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    #- name: Download generated data
    #  uses: actions/download-artifact@v4
    #  with:
    #    name: generated-data
    #    path: data/

    - name: Use Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: 24
    - name: Install dependencies
      run: npm ci
    - name: Build UI
      run: npm run build
